Repository LouanBen/wordle-fr, pull requests merged in 2022-04, with the labels that each got.

#51 Fait marcher le bouton Partager sur les vieux navigateurs
  src/components/Game.vue
Labels: PR : approved

#45 Close modals on backdrop click
  src/components/Game.vue
Labels: PR : approved

#38 Interactive keyboard & colorblind mode modifications
  package-lock.json
  src/components/grid/LetterContainer.vue
  src/components/keyboard/Key.vue
Labels: PR : approved

#42 Design improvements
  src/components/Game.vue
  src/components/grid/LetterContainer.vue
  src/components/keyboard/Key.vue
Labels: PR : changes requested

#47 Redesign archive
  src/components/Game.vue
Labels: PR : in discussion
